### ISSUE TITLE
gen.vector.char error

### ISSUE THREAD

**Issue by ggrothendieck** [patrickroocks/listcompr#1]
This gives an error:

```
> # ok
> library(listcompr)
> gen.vector((i + j), i = 1:3, j = 1:3)
[1] 2 3 4 3 4 5 4 5 6

> # error
> gen.vector.char(as.character(i + j), i = 1:3, j = 1:3)
Error in gen_list_internal(str, l, TRUE, OUTPUT_FORMAT$CHAR, NULL, parent.frame()) : 
  object 'i' not found
```

Also this gives an error.  Can one only iterate over numerics?

```
> gen.list(paste(v, v), v = month.abb)
Error: could not evaluate variable range of 'v', got 'month.abb', expected something like start_expr:end_expr, did not find numeric vector
```

**Comment by patrickroocks** [comment]
Thanks for the feedback!

`gen.vector.char` expects a character as base expression, where all expressions to be evaluated are in {}-brackets.

In your example:

    > gen.vector.char("{i + j}", i = 1:3, j = 1:3)
    [1] "2" "3" "4" "3" "4" "5" "4" "5" "6"

I will make the error message clearer in this case.

Regarding the second error:

Yes, currently the variable range has to be numeric. I will remove this restriction in the future!

**Comment by patrickroocks** [comment]
Added support for character variable ranges in v0.1.1. Slightly changed the help for `gen.vector.char` to make it a bit more clear that a character is expected as base expression.
