### ISSUE TITLE
combining columns

### ISSUE THREAD

**Issue by ggrothendieck** [patrickroocks/listcompr#4]
The following code works and gives the desired result.

```
nms <- names(BOD)
as.data.frame(gen.named.list("{nms[i]}.{nms[j]}", as.list(BOD)[[i]] + as.list(BOD)[[j]], i = 1:2, j = 1:2))
##   Time.Time demand.Time Time.demand demand.demand
## 1         2         9.3         9.3          16.6
## 2         4        12.3        12.3          20.6
## 3         6        22.0        22.0          38.0
## 4         8        20.0        20.0          32.0
## 5        10        20.6        20.6          31.2
## 6        14        26.8        26.8          39.6
```

however, it was necessary as far as I understand to convert the data frame to list and back if one wants to operate on columns rather than rows.  I initially tried this but then realized it does not work as I had intended.  Maybe there could be some facility to allow one to easily operate on columns and get columns?

```
gen.named.data.frame("{nms[i]}.{nms[j]}", BOD[[i]] + BOD[[j]], i = 1:2, j = 1:2)) # nms defined above

##                 V1   V2 V3 V4   V5   V6
## Time.Time      2.0  4.0  6  8 10.0 14.0
## demand.Time    9.3 12.3 22 20 20.6 26.8
## Time.demand    9.3 12.3 22 20 20.6 26.8
## demand.demand 16.6 20.6 38 32 31.2 39.6
```

**Comment by patrickroocks** [comment]
Ok, you finally convinced me that it might be a good idea to allow the data set generation by columns and not only by rows :)

I just added the `bycol` parameter to the `gen.(named).(data.frame|matrix)` functions, which applies the Cartesian of the input variables to the given expression by rows and not by columns. Implicitly the names within the `get.named.*` functions refer to the column names and not to the row names:

    > gen.named.data.frame("{nms[i]}.{nms[j]}", BOD[[i]] + BOD[[j]], i = 1:2, j = 1:2, bycol = TRUE)
         Time.Time demand.Time Time.demand demand.demand
    [1,]         2         9.3         9.3          16.6
    [2,]         4        12.3        12.3          20.6
    [3,]         6        22.0        22.0          38.0
    [4,]         8        20.0        20.0          32.0
    [5,]        10        20.6        20.6          31.2
    [6,]        14        26.8        26.8          39.6

Added with my last commit, documentation for the new feature is work in progress.

**Comment by patrickroocks** [comment]
As the elements of inner vector refers to the columns and not to the rows, I decided to rename `bycol` to `byrow`.

We now have: 

    > nms <- names(BOD)
    > gen.named.data.frame("{nms[i]}.{nms[j]}", BOD[[i]] + BOD[[j]], i = 1:2, j = 1:2, byrow = TRUE)
         Time.Time demand.Time Time.demand demand.demand
    [1,]         2         9.3         9.3          16.6
    [2,]         4        12.3        12.3          20.6
    [3,]         6        22.0        22.0          38.0
    [4,]         8        20.0        20.0          32.0
    [5,]        10        20.6        20.6          31.2
    [6,]        14        26.8        26.8          39.6
